INSERT INTO ADDRESS_BOOK (ADDRESS_BOOK_NAME) VALUES ('ADDRESS_BOOK_1');
INSERT INTO ADDRESS_BOOK (ADDRESS_BOOK_NAME) VALUES ('ADDRESS_BOOK_2');
INSERT INTO ADDRESS_BOOK (ADDRESS_BOOK_NAME) VALUES ('ADDRESS_BOOK_3');

INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Harry', '7860489023', 'ADDRESS_BOOK_1');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Mary', '8958362904', 'ADDRESS_BOOK_1');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Jane', '9473829485', 'ADDRESS_BOOK_1');

INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Mary', '7938294058', 'ADDRESS_BOOK_2');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('John', '6438749302', 'ADDRESS_BOOK_2');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Jane', '8493938474', 'ADDRESS_BOOK_2');

INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Peter', '9372812473', 'ADDRESS_BOOK_3');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Mary', '6392048506', 'ADDRESS_BOOK_3');
INSERT INTO CONTACT_DETAILS (FULL_NAME, PHONE_NUMBER, ADDRESS_BOOK_NAME) VALUES ('Jane', '8463821749', 'ADDRESS_BOOK_3');
